<?php
    $_products = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<h1 class="mosaic-title"><?php echo Mage::getStoreConfig('general/store_information/name') ?></h1>

<div id="mosaic_container">
    <?php foreach($_products as $_product): ?>
        <div class="box col<?php echo rand(1, 3) ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(500); ?>" />
            <div style="display:none" class="details">
                <h1><?php echo $_product->getName() ?></h1>
                <p><?php echo $_product->getShortDescription() ?></p>
                <p><?php echo Mage::helper('core')->currency($_product->getPrice()) ?></p>
            </div>
        </div>
    <?php endforeach ?>
</div>


<script type="text/javascript">
    var largeSize="480px";
    $j(function() {
        $j('#mosaic_container').masonry({
            itemSelector: '.box',
            columnWidth: 100,
            isAnimated: true,
            animationOptions: {
                complete: function() {
                    if ($j(this).hasClass('clicked')) {
                        $j(this).animate({width: largeSize, height: largeSize}, 1000, function() {
                            $j('#mosaic_container').masonry('reload');
                            $j(this).removeClass('clicked');
                            $j(this).addClass('expanded');
                            $j(this).find('.details').fadeIn(100)
                        });
                    }
                }
            }
        });

        $j('#mosaic_container .box').each(function () {
            var el = $j(this);

            el.data('original_width', el.width());
            el.data('original_height', el.height());
        })

        $j('#mosaic_container .box').click(function() {
            if ($j(this).hasClass('expanded')) return;

            var expanded = $j('#mosaic_container .box.expanded');

            expanded.animate({width: expanded.data('original_width'), height: expanded.data('original_height'), zIndex: ''}, 1000);
            expanded.find('img').animate({width: expanded.data('original_width'), height: expanded.data('original_height'), zIndex: ''}, 1000);
            expanded.find('.details').fadeOut(100);

            $j('#mosaic_container .box').removeClass('expanded');

            $j(this).css({zIndex: 999});
            $j(this).addClass('clicked');

            if ($j(this).prev().length > 0) {
                $j('#mosaic_container .box').first().before(this);
            }

            $j('#mosaic_container').masonry('reload');
        })
    })
</script>